[2023-12-03 21:30:55,201][urllib3.connectionpool][WARNING] - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13383ac10>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/2.0/mlflow/experiments/create
[2023-12-03 21:30:59,205][urllib3.connectionpool][WARNING] - Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13383ad60>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/2.0/mlflow/experiments/create
[2023-12-03 21:31:07,208][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x13383ad30>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/2.0/mlflow/experiments/create
[2023-12-03 21:31:23,215][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1338498e0>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/2.0/mlflow/experiments/create
[2023-12-03 21:31:55,221][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x133849340>: Failed to establish a new connection: [Errno 61] Connection refused')': /api/2.0/mlflow/experiments/create
